### ISSUE TITLE
master package get后任然无法运行

### ISSUE THREAD

**Issue by ddwhan0123** [lizubing1992/flutter_bloc#1]
错误信息如下
ListFooterView 文件 OnLoading对象未定义
<img width="1352" alt="屏幕快照 2019-11-20 上午9 49 58" src="https://user-images.githubusercontent.com/9019351/69202041-4a151500-0b7b-11ea-974d-8617824bdc09.png">

**Comment by lizubing1992** [comment]
重新拉一下代码，升级了一下刷新控件，就没这个问题了
